### ISSUE TITLE
Request: Page width relative videos per row

### ISSUE THREAD

**Issue by Catman-232** [sapondanaisriwan/youtube-row-fixer#11]
I've been struggling for hours trying to edit the AdashimaaTube Stylus style to somehow make the videos per row be relative to the width of the page, I just couldn't figure it out and tried this instead only to find it does the tweak the same way. I have Youtube at 90% zoom and I usually have my web browser set to half of the monitor size (Drag the window into the left or right edge of your screen) which means that if the videos per row is forced to whatever number, it still does that when the page width is half as much. By default Youtube actually shows a different amount per row in this use case but they're obviously shitty with five per row wide and when halfscreen just two per row!

I used to have a tampermonkey script that would instead edit the thumbnail size and then set the amount of videos per row based upon that, meaning I could have seven in a row when it's expanded, but four when it's halfscreen. I don't know what happened to it but it's gone and I have no idea how it even worked, so I'm making the request here in case it's possible to add as an option for this extension.

**Comment by sapondanaisriwan** [comment]
I have no idea how to get it works with this extension since I'm not quite good at JS.

I hope this meets your expectations. You can make a new style in the stylus extension and insert this code into the editor.
Tips: AdashimaaTube have a dynamic video per row on the [search page](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/5c2177bc-96f8-4a1d-9aef-63b440ab0d00).
```css
[page-subtype="home"] #contents.ytd-rich-grid-renderer {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(246px, 1fr));
  justify-items: center;
  gap: 16px;
}
[page-subtype="home"] ytd-rich-grid-row,
[page-subtype="home"] ytd-rich-grid-row #contents.ytd-rich-grid-row {
  display: contents !important;
}
[page-subtype="home"] #contents.ytd-rich-grid-renderer {
  width: calc(100% - 1.6rem);
  max-width: calc(var(--ytd-rich-grid-items-per-row) * (var(--ytd-rich-grid-item-max-width) + var(--ytd-rich-grid-item-margin)));
}
[page-subtype="home"] ytd-rich-item-renderer {
  display: none;
}
[page-subtype="home"] ytd-rich-section-renderer {
  display: none;
}
```
**Before**
![17-03-24_11-50](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/186387f2-8202-4a53-9bd4-6fc28fe1b963)

**After**
![MJ3QyiRgJ9](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/8bb50aa6-b5c1-4672-b6c0-3d7fc03d87db)

![17-03-24_11-48](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/5a7391c6-9334-47b6-b508-830fe30bbc21)
